In [76]:
import pandas as pd
from glob import glob

# Read single CSV file
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")
single_file_gyr = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

# List all data in data/raw/MetaMotion
files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

# Extract features from filename
data_path = "../../data/raw/MetaMotion"
f = files[10]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123")

In [43]:
single_file_acc

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547472169751,2019-01-14T14:22:49.751,0.00,-0.147,0.702,-0.276
1,1547472169831,2019-01-14T14:22:49.831,0.08,-0.120,0.710,-0.360
2,1547472169911,2019-01-14T14:22:49.911,0.16,-0.160,0.768,-0.392
3,1547472169991,2019-01-14T14:22:49.991,0.24,-0.208,0.817,-0.379
4,1547472170071,2019-01-14T14:22:50.071,0.32,-0.223,0.839,-0.403
...,...,...,...,...,...,...
147,1547472181511,2019-01-14T14:23:01.511,11.76,-0.068,0.933,-0.345
148,1547472181591,2019-01-14T14:23:01.591,11.84,-0.075,0.903,-0.349
149,1547472181671,2019-01-14T14:23:01.671,11.92,-0.070,0.899,-0.361
150,1547472181751,2019-01-14T14:23:01.751,12.00,-0.067,0.941,-0.365
151,1547472181831,2019-01-14T14:23:01.831,12.08,-0.083,0.938,-0.366

In [44]:
single_file_gyr

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s)
0,1547472420993,2019-01-14T14:27:00.993,0.00,2.317,-2.500,-9.695
1,1547472421033,2019-01-14T14:27:01.033,0.04,3.110,-0.793,-9.207
2,1547472421073,2019-01-14T14:27:01.073,0.08,3.232,2.134,-2.500
3,1547472421113,2019-01-14T14:27:01.113,0.12,2.988,2.195,-11.159
4,1547472421153,2019-01-14T14:27:01.153,0.16,18.354,-7.866,-14.451
...,...,...,...,...,...,...
315,1547472433593,2019-01-14T14:27:13.593,12.60,6.159,-0.244,1.463
316,1547472433633,2019-01-14T14:27:13.633,12.64,5.976,-1.768,0.549
317,1547472433673,2019-01-14T14:27:13.673,12.68,9.878,-2.317,1.037
318,1547472433713,2019-01-14T14:27:13.713,12.72,7.683,-1.951,-2.439
319,1547472433753,2019-01-14T14:27:13.753,12.76,9.939,-1.402,3.659

In [45]:
files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

187

In [46]:
participant, label

('\\A', 'dead')

In [47]:
participant = f.split("-")[0].split("-")[0].replace(data_path+"\\", "")

In [48]:
"\\" + data_path

'\\../../data/raw/MetaMotion'

In [49]:
label

'dead'

In [50]:
category

'medium'

In [51]:
"fdasnlnabv3".rstrip("123")

'fdasnlnabv'

In [52]:
df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label
df["category"] = category

In [53]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547223864873,2019-01-11T17:24:24.873,0.00,0.027,-1.009,-0.108,A,dead,medium
1,1547223864953,2019-01-11T17:24:24.953,0.08,0.086,-1.045,-0.223,A,dead,medium
2,1547223865033,2019-01-11T17:24:25.033,0.16,0.055,-1.039,-0.205,A,dead,medium
3,1547223865113,2019-01-11T17:24:25.113,0.24,0.068,-1.022,-0.140,A,dead,medium
4,1547223865193,2019-01-11T17:24:25.193,0.32,0.097,-1.014,-0.121,A,dead,medium
...,...,...,...,...,...,...,...,...,...
353,1547223895513,2019-01-11T17:24:55.513,30.64,-0.012,-1.012,-0.219,A,dead,medium
354,1547223895593,2019-01-11T17:24:55.593,30.72,-0.005,-1.025,-0.167,A,dead,medium
355,1547223895673,2019-01-11T17:24:55.673,30.80,0.015,-1.015,-0.168,A,dead,medium
356,1547223895753,2019-01-11T17:24:55.753,30.88,0.005,-1.022,-0.176,A,dead,medium
357,1547223895833,2019-01-11T17:24:55.833,30.96,-0.002,-1.026,-0.189,A,dead,medium

In [74]:
import pandas as pd
from glob import glob

# Read single CSV file
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")
single_file_gyr = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

# List all data in data/raw/MetaMotion
files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

# Extract features from filename
data_path = "../../data/raw/MetaMotion"
f = files[0]

participant = f.split("-")[0].split("-")[0].replace(data_path+"\\", "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label
df["category"] = category

# Read all files
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

for f in files:

    participant = f.split("-")[0].split("-")[0].replace(data_path+"\\", "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123")

    df = pd.read_csv(f)

    df['participant'] =  participant
    df['label'] = label
    df['category'] = category


df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,E,squat,heavy_MetaWear_2019
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,E,squat,heavy_MetaWear_2019
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,E,squat,heavy_MetaWear_2019
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,E,squat,heavy_MetaWear_2019
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,E,squat,heavy_MetaWear_2019
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,E,squat,heavy_MetaWear_2019
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,E,squat,heavy_MetaWear_2019
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,E,squat,heavy_MetaWear_2019
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,E,squat,heavy_MetaWear_2019
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,E,squat,heavy_MetaWear_2019

In [77]:
df['category']

0      heavy_MetaWear_2019
1      heavy_MetaWear_2019
2      heavy_MetaWear_2019
3      heavy_MetaWear_2019
4      heavy_MetaWear_2019
              ...
487    heavy_MetaWear_2019
488    heavy_MetaWear_2019
489    heavy_MetaWear_2019
490    heavy_MetaWear_2019
491    heavy_MetaWear_2019
Name: category, Length: 492, dtype: object

In [87]:
import pandas as pd
from glob import glob

# Read single CSV file
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")
single_file_gyr = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

# List all data in data/raw/MetaMotion
files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

# Extract features from filename
data_path = "../../data/raw/MetaMotion"
f = files[0]

participant = f.split("-")[0].split("-")[0].replace(data_path+"\\", "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label
df["category"] = category

# Read all files
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:

    participant = f.split("-")[0].replace(data_path+"\\", "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df['participant'] = participant
    df['label'] = label
    df['category'] = category

    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])
    elif "Gyroscope" in f:
        gyr_df = pd.concat([gyr_df, df])

In [88]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [93]:
acc_df[:210]

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108,A,bench,heavy,1
0,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383,A,bench,heavy,2
1,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424,A,bench,heavy,2
2,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421,A,bench,heavy,2
3,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439,A,bench,heavy,2

In [90]:
pd.read_csv(files[0])

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094
...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108

In [95]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,E,squat,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,E,squat,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,E,squat,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,E,squat,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,E,squat,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,E,squat,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,E,squat,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,E,squat,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,E,squat,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,E,squat,heavy

In [107]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [102]:
1547221297570 -  	1547221285010

12560

In [109]:
def read_data_from_files(files):

    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()

    acc_set = 1
    gyr_set = 1

    for f in files:

        participant = f.split("-")[0].replace(data_path+"\\" , "")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

        df = pd.read_csv(f)

        df["participant"] = participant
        df["label"] = label
        df["category"] = category

        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])

        elif "Gyroscope" in f:
            df["set"] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])

    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]
    del acc_df["elapsed (s)"]

    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]
    del gyr_df["elapsed (s)"]

    return acc_df, gyr_df

acc_df, gyr_df = read_data_from_files(files)

In [117]:
acc_df[:14]

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
2019-01-11 15:10:08.831,-0.017,0.902,-0.108,A,bench,heavy,1
2019-01-11 15:10:08.911,-0.025,0.855,-0.128,A,bench,heavy,1
2019-01-11 15:10:08.991,-0.042,0.844,-0.139,A,bench,heavy,1
2019-01-11 15:10:09.071,-0.049,0.875,-0.171,A,bench,heavy,1
2019-01-11 15:10:09.151,-0.075,0.871,-0.139,A,bench,heavy,1
2019-01-11 15:10:09.231,-0.083,0.895,-0.174,A,bench,heavy,1
2019-01-11 15:10:09.311,-0.089,0.901,-0.183,A,bench,heavy,1
2019-01-11 15:10:09.391,-0.118,0.917,-0.150,A,bench,heavy,1
2019-01-11 15:10:09.471,-0.120,0.957,-0.183,A,bench,heavy,1

In [118]:
gyr_df.dtypes

x-axis (deg/s)    float64
y-axis (deg/s)    float64
z-axis (deg/s)    float64
participant        object
label              object
category           object
set                 int64
dtype: object

In [129]:
merged_df = pd.concat([acc_df.iloc[:, :3], gyr_df], axis=1)   
                                                              
merged_df.columns = [                                         
    "acc_x",                                                  
    "acc_y",                                                  
    "acc_z",                                                  
    "gyr_x",                                                  
    "gyr_y",                                                  
    "gyr_z",                                                  
    "participant",
    "label",
    "category",
    "set",                                                    
]                                                             
                                                              
                                                              
# Resample data (frequency conversion)                        
# Accelerometer:12.500HZ - Gyroscope:25.000Hz                 
sampling = {                                                  
    "acc_x": "mean",                                          
    "acc_y": "mean",                                          
    "acc_z": "mean",                                          
    "gyr_x": "mean",                                          
    "gyr_y": "mean",                                          
    "gyr_z": "mean",                                          
    "label": "last",                                          
    "category": "last",                                       
    "participant": "last",                                    
    "set": "last"                                             
}                                                             
# merged_df = merged_df.select_dtypes([int, float]).resample(r
# merged_df.dropna(inplace=True)                              
# print(merged_df) # But we have lost alot of data, so we will
                                                              
merged_df.resample(rule="100ms").apply(sampling)              
                                                              
days = [g for n, g in merged_df.groupby(pd.Grouper(freq="D"))]
days[0]

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 16:24:55.706,NaN,NaN,NaN,-8.415,7.683,4.207,A,dead,medium,6.0
2019-01-11 16:24:55.746,NaN,NaN,NaN,-4.573,-5.732,2.744,A,dead,medium,6.0
2019-01-11 16:24:55.753,0.005,-1.022,-0.176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 16:24:55.786,NaN,NaN,NaN,1.463,-12.195,-0.305,A,dead,medium,6.0
2019-01-11 16:24:55.833,-0.002,-1.026,-0.189,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
data_resampled = pd.concat([df.resample(rule="100ms").apply(sampling).dropna() for df in days])
data_resampled

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.300,0.0135,0.9770,-0.071,-1.524333,3.069333,4.573000,bench,heavy,B,30.0
2019-01-11 15:08:05.400,-0.0110,0.9700,-0.086,0.732000,-2.104000,-0.518500,bench,heavy,B,30.0
2019-01-11 15:08:05.500,0.0080,0.9710,-0.073,-3.292333,-0.081333,3.963667,bench,heavy,B,30.0
2019-01-11 15:08:05.600,0.0120,0.9960,-0.051,-8.597500,-2.774500,-1.006000,bench,heavy,B,30.0
2019-01-11 15:08:05.700,-0.0040,0.9595,-0.071,9.999667,1.423000,-1.687000,bench,heavy,B,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.400,-0.0560,-1.0260,-0.072,3.394333,-10.162667,0.264333,row,medium,E,90.0
2019-01-20 17:33:27.500,-0.0640,-1.0360,-0.092,2.012500,2.408500,-0.701500,row,medium,E,90.0
2019-01-20 17:33:27.600,-0.0345,-1.0285,-0.042,0.081333,-0.650333,2.215333,row,medium,E,90.0
2019-01-20 17:33:27.700,-0.0470,-1.0200,-0.050,-0.701500,1.616000,-0.518000,row,medium,E,90.0
2019-01-20 17:33:27.800,-0.0440,-1.0340,-0.059,1.098000,-4.024000,0.976000,row,medium,E,90.0